//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Ressources/Inputs/ControlsGame.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlsGame : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlsGame()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlsGame"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""badf78c4-12bb-4c95-9fe9-4f76f7222553"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c9d592c4-3606-4b6b-acd8-9bcb186541d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Card 1"",
                    ""type"": ""Button"",
                    ""id"": ""8c20feab-b7cf-4937-8058-96daaab38f5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Card 2"",
                    ""type"": ""Button"",
                    ""id"": ""f65d5b3b-c4f8-41ff-8748-3e44982c445c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Card 3"",
                    ""type"": ""Button"",
                    ""id"": ""00ff60e6-e9b3-4d5c-b8db-c06e69c11f88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Card 4"",
                    ""type"": ""Button"",
                    ""id"": ""babf6a44-ed0c-41a1-89d2-721a8c32408b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Card 5"",
                    ""type"": ""Button"",
                    ""id"": ""fc3a82db-2c2f-47f4-a146-1016f97dbc33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""b5253e36-f211-4a6f-9ab9-ffcad625045e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8fe62b2-b5c0-4e2e-a7a4-59bd81201472"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5baa6a17-7ab5-4474-9ad5-87b64987ad8a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a81a7de9-7ea7-41cb-b635-4d02cf7c79e8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9b978f0f-3579-434a-b053-e232c9dd16d4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4e975425-a6c2-4749-83fb-7d03ec10ff08"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""021f576b-edae-4362-adfd-a70a6f3b86bb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b20410b1-767b-4c4d-bf75-bb5dd7a85fe9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""aaafbc4e-aa42-4d73-9e2c-ab100464f820"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d5d02f6c-31b4-41a7-9860-426fb09b1abb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0493c532-ead5-42b7-9a09-f539b8ab9771"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""18388379-4c58-4a37-92f2-9b941e612457"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""24ab9114-279f-4db1-b676-5421aa56d0ce"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d2de7762-f1bb-45e7-b795-eb4e8b2fdad6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4520355c-c06a-411b-9d99-1409f45dc686"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3672c580-e9dd-4419-8f92-892398d7e55d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""030f01be-c4f3-400f-b3f7-8bc101923d9a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05e60179-8581-44bd-a600-0c02fbd8fc17"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fff32c3-0434-497b-b050-6a7e80c2bb76"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e728f4b1-30cb-4b44-b6d9-45b7d4a7c7e6"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf961f05-b088-4799-a945-cacb096d2e31"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c4b7d97-d660-47e8-b8f6-d9e8de7cab4f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deacf0a0-7f46-43d3-b494-d2d2f26f3382"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""716bfb5c-0e3b-45f6-b09b-afb2bf94a35d"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1be700e2-974c-48fc-8d0f-270a245c1d39"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae8bcad4-f45d-4339-80d0-1080e99bd22a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42e58804-6913-4a4d-a27e-ddceb82991c3"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9da06a98-aa36-4db4-a7b5-96c31b9d482c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Card 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9828efae-927d-40fd-8638-16b137d4e2d7"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Card1 = m_Player.FindAction("Card 1", throwIfNotFound: true);
        m_Player_Card2 = m_Player.FindAction("Card 2", throwIfNotFound: true);
        m_Player_Card3 = m_Player.FindAction("Card 3", throwIfNotFound: true);
        m_Player_Card4 = m_Player.FindAction("Card 4", throwIfNotFound: true);
        m_Player_Card5 = m_Player.FindAction("Card 5", throwIfNotFound: true);
        m_Player_Submit = m_Player.FindAction("Submit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Card1;
    private readonly InputAction m_Player_Card2;
    private readonly InputAction m_Player_Card3;
    private readonly InputAction m_Player_Card4;
    private readonly InputAction m_Player_Card5;
    private readonly InputAction m_Player_Submit;
    public struct PlayerActions
    {
        private @ControlsGame m_Wrapper;
        public PlayerActions(@ControlsGame wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Card1 => m_Wrapper.m_Player_Card1;
        public InputAction @Card2 => m_Wrapper.m_Player_Card2;
        public InputAction @Card3 => m_Wrapper.m_Player_Card3;
        public InputAction @Card4 => m_Wrapper.m_Player_Card4;
        public InputAction @Card5 => m_Wrapper.m_Player_Card5;
        public InputAction @Submit => m_Wrapper.m_Player_Submit;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Card1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard1;
                @Card1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard1;
                @Card1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard1;
                @Card2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard2;
                @Card2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard2;
                @Card2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard2;
                @Card3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard3;
                @Card3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard3;
                @Card3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard3;
                @Card4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard4;
                @Card4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard4;
                @Card4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard4;
                @Card5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard5;
                @Card5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard5;
                @Card5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCard5;
                @Submit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmit;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Card1.started += instance.OnCard1;
                @Card1.performed += instance.OnCard1;
                @Card1.canceled += instance.OnCard1;
                @Card2.started += instance.OnCard2;
                @Card2.performed += instance.OnCard2;
                @Card2.canceled += instance.OnCard2;
                @Card3.started += instance.OnCard3;
                @Card3.performed += instance.OnCard3;
                @Card3.canceled += instance.OnCard3;
                @Card4.started += instance.OnCard4;
                @Card4.performed += instance.OnCard4;
                @Card4.canceled += instance.OnCard4;
                @Card5.started += instance.OnCard5;
                @Card5.performed += instance.OnCard5;
                @Card5.canceled += instance.OnCard5;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCard1(InputAction.CallbackContext context);
        void OnCard2(InputAction.CallbackContext context);
        void OnCard3(InputAction.CallbackContext context);
        void OnCard4(InputAction.CallbackContext context);
        void OnCard5(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
}
